# Generated by Django 4.2.11 on 2024-03-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_task_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='PostsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='avatars/default_user.png', upload_to='img/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='task_manager.task')),
            ],
        ),
    ]
