# Generated by Django 4.2.11 on 2024-03-18 14:30

from django.db import migrations, models
import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_task_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.ImageField(default='uploads/images/no-photo-task.jpg', upload_to=task_manager.models.create_custom_path),
        ),
        migrations.DeleteModel(
            name='PostsImages',
        ),
    ]
