# Generated by Django 4.2.11 on 2024-03-24 16:49

from django.db import migrations, models
import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_task_task_image_delete_postsimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='worker',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', upload_to=task_manager.models.create_avatar_path),
        ),
    ]
